/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import static com.sun.deploy.uitoolkit.impl.fx.ui.MixedCodeInSwing.show;
import java.awt.Color;
import java.awt.Dimension;
import static java.lang.Compiler.disable;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author albi mudakar
 */
public class selamatDatang extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public selamatDatang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jpanelBarista21552011235 = new javax.swing.JPanel();
        CloseBtn21552011235 = new javax.swing.JLabel();
        SelamatDatang = new javax.swing.JLabel();
        IconLangkop = new javax.swing.JLabel();
        Sistem = new javax.swing.JLabel();
        sidoma = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        line = new javax.swing.JLabel();
        panelPetugas21552011235 = new javax.swing.JPanel();
        BtnPetugas21552011235 = new javax.swing.JLabel();
        panelAdmin21552011235 = new javax.swing.JPanel();
        BtnAdmin21552011235 = new javax.swing.JLabel();
        versi = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        Developed1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LoadingLabel = new javax.swing.JLabel();
        hexa = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelBarista21552011235.setBackground(new java.awt.Color(17, 43, 60));
        jpanelBarista21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseBtn21552011235.setBackground(new java.awt.Color(0, 0, 0));
        CloseBtn21552011235.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-close-32.png"))); // NOI18N
        CloseBtn21552011235.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseBtn21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBtn21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseBtn21552011235MouseEntered(evt);
            }
        });
        jpanelBarista21552011235.add(CloseBtn21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        SelamatDatang.setBackground(new java.awt.Color(255, 255, 255));
        SelamatDatang.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        SelamatDatang.setForeground(new java.awt.Color(255, 255, 255));
        SelamatDatang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelamatDatang.setText("Selamat Datang");
        jpanelBarista21552011235.add(SelamatDatang, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        IconLangkop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/map-majalaya-logo-FIKS.png"))); // NOI18N
        jpanelBarista21552011235.add(IconLangkop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 290, 250));

        Sistem.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Sistem.setForeground(new java.awt.Color(255, 255, 255));
        Sistem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sistem.setText("Di Sistem Informasi Donor Darah Majalaya");
        jpanelBarista21552011235.add(Sistem, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 330, 36));

        sidoma.setBackground(new java.awt.Color(0, 0, 0));
        sidoma.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        sidoma.setForeground(new java.awt.Color(255, 255, 255));
        sidoma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sidoma.setText("SIDOMA");
        jpanelBarista21552011235.add(sidoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 120, 36));

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("LOGIN ");
        jpanelBarista21552011235.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 60, 36));

        line.setBackground(new java.awt.Color(255, 255, 255));
        line.setForeground(new java.awt.Color(255, 255, 255));
        line.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        line.setText("____________");
        jpanelBarista21552011235.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 100, 20));

        panelPetugas21552011235.setBackground(new java.awt.Color(17, 43, 60));
        panelPetugas21552011235.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        panelPetugas21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnPetugas21552011235.setBackground(new java.awt.Color(17, 43, 60));
        BtnPetugas21552011235.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        BtnPetugas21552011235.setForeground(new java.awt.Color(255, 255, 255));
        BtnPetugas21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnPetugas21552011235.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-male-user-24.png"))); // NOI18N
        BtnPetugas21552011235.setText("Petugas");
        BtnPetugas21552011235.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnPetugas21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPetugas21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnPetugas21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnPetugas21552011235MouseExited(evt);
            }
        });
        panelPetugas21552011235.add(BtnPetugas21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jpanelBarista21552011235.add(panelPetugas21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 120, 40));

        panelAdmin21552011235.setBackground(new java.awt.Color(17, 43, 60));
        panelAdmin21552011235.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        panelAdmin21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnAdmin21552011235.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        BtnAdmin21552011235.setForeground(new java.awt.Color(255, 255, 255));
        BtnAdmin21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnAdmin21552011235.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-male-user-24.png"))); // NOI18N
        BtnAdmin21552011235.setText("Admin");
        BtnAdmin21552011235.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAdmin21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAdmin21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAdmin21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAdmin21552011235MouseExited(evt);
            }
        });
        panelAdmin21552011235.add(BtnAdmin21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jpanelBarista21552011235.add(panelAdmin21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 120, 40));

        versi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        versi.setForeground(new java.awt.Color(255, 255, 255));
        versi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versi.setText("v1.0");
        jpanelBarista21552011235.add(versi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 80, 30));

        LoadingValue.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(255, 255, 255));
        LoadingValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoadingValue.setText("0%");
        jpanelBarista21552011235.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 40, 36));

        LoadingBar.setBackground(new java.awt.Color(255, 0, 0));
        jpanelBarista21552011235.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 530, 10));

        Developed1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Developed1.setForeground(new java.awt.Color(255, 255, 255));
        Developed1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Developed1.setText("Developed By © Kelompok II  2022");
        jpanelBarista21552011235.add(Developed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 240, 36));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/colorRED1234.png"))); // NOI18N
        jpanelBarista21552011235.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 290, 40));

        LoadingLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        LoadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        LoadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LoadingLabel.setText("Loading...");
        jpanelBarista21552011235.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 280, 36));

        hexa.setBackground(new java.awt.Color(255, 255, 255));
        hexa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HEXABACKCONNECT.png"))); // NOI18N
        jpanelBarista21552011235.add(hexa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 520, 440));

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linePNG.png"))); // NOI18N
        jpanelBarista21552011235.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 440));

        getContentPane().add(jpanelBarista21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 813, -1));

        setSize(new java.awt.Dimension(813, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    
    private void CloseBtn21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtn21552011235MouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBtn21552011235MouseClicked

    private void CloseBtn21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtn21552011235MouseEntered
       
    }//GEN-LAST:event_CloseBtn21552011235MouseEntered

    private void BtnAdmin21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAdmin21552011235MouseClicked
        new login.loginAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnAdmin21552011235MouseClicked

    private void BtnAdmin21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAdmin21552011235MouseEntered
       changecolor(panelAdmin21552011235, new Color (32,83,117));
    }//GEN-LAST:event_BtnAdmin21552011235MouseEntered

    private void BtnAdmin21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAdmin21552011235MouseExited
        changecolor(panelAdmin21552011235, new Color (17,43,60));
    }//GEN-LAST:event_BtnAdmin21552011235MouseExited

    private void BtnPetugas21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPetugas21552011235MouseClicked
        new login.loginPetugas().setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnPetugas21552011235MouseClicked

    private void BtnPetugas21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPetugas21552011235MouseEntered
        changecolor(panelPetugas21552011235, new Color (32,83,117));
    }//GEN-LAST:event_BtnPetugas21552011235MouseEntered

    private void BtnPetugas21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPetugas21552011235MouseExited
         changecolor(panelPetugas21552011235, new Color (17,43,60));
    }//GEN-LAST:event_BtnPetugas21552011235MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        selamatDatang sp = new selamatDatang();
        sp.setVisible(true);
        
        try {
            for (int i=0;i<=100;i++){
                Thread.sleep(100);
                sp.LoadingValue.setText(i+ "%");
                
                if (i==10){
                    sp.LoadingLabel.setText("Turning On Module...");
                }
                
                if (i==20){
                   sp.LoadingLabel.setText("Loading Module...");
                }
                
                if (i==30){
                    sp.LoadingLabel.setText("Connecting To Database...");
                }
                
                if (i==80){
                    sp.LoadingLabel.setText("Connecting Successfull...");
                }
                
                 if (i==90){
                     sp.LoadingLabel.setText("Launching Application SIDOMA...");
                 }
                 
                 sp.LoadingBar.setValue(i);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnAdmin21552011235;
    private javax.swing.JLabel BtnPetugas21552011235;
    private javax.swing.JLabel CloseBtn21552011235;
    private javax.swing.JLabel Developed1;
    private javax.swing.JLabel IconLangkop;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel SelamatDatang;
    private javax.swing.JLabel Sistem;
    private javax.swing.JLabel hexa;
    private javax.swing.JLabel image;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpanelBarista21552011235;
    private javax.swing.JLabel line;
    private javax.swing.JPanel panelAdmin21552011235;
    private javax.swing.JPanel panelPetugas21552011235;
    private javax.swing.JLabel sidoma;
    private javax.swing.JLabel versi;
    // End of variables declaration//GEN-END:variables

    private void changecolor(JLabel CloseBtn21552011235, Color color) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
