/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sekretaris;

import sekretaris.*;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author albi mudakar
 */
public class dashboardSekretaris extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    boolean a= true;
    public dashboardSekretaris() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        //usernameSekretaris21552011235.setText();
    }




    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        headerKelompok2 = new javax.swing.JPanel();
        iconMenu = new javax.swing.JPanel();
        PanelLogout21552011235 = new javax.swing.JPanel();
        BtnLogout21552011235 = new javax.swing.JLabel();
        BtnMax21552011235 = new javax.swing.JPanel();
        BtnMin21552011235 = new javax.swing.JPanel();
        menuKelompok2 = new javax.swing.JPanel();
        sidebarKelompok2 = new javax.swing.JPanel();
        homePanelKelompok2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnHomeKelompok2 = new javax.swing.JLabel();
        DataPanelKelompok2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        BtnDataKelompok2 = new javax.swing.JLabel();
        pagePrintKelompok2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BtnPrintKelompok2 = new javax.swing.JLabel();
        aboutPanelKelompok2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        BtnAboutKelompok2 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        DashboardviewKelompok2 = new javax.swing.JPanel();
        jTabbedPanelKelompok2 = new javax.swing.JTabbedPane();
        HomeTabbedKelompok2 = new javax.swing.JPanel();
        IconUser = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DataTabbedKelompok2 = new javax.swing.JPanel();
        TabHomePanelKegiatan = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        TabKegiatanKelompok2 = new javax.swing.JLabel();
        TabPanelPetugasKelompok2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        TabPetugasKelompok2 = new javax.swing.JLabel();
        PagePrintTabbedKelompok2 = new javax.swing.JPanel();
        PanelKeuanganMasukKelompok2 = new javax.swing.JPanel();
        TabKeuanganMasukBtnKelompok2 = new javax.swing.JLabel();
        PanelUserKelompok2 = new javax.swing.JPanel();
        TabUserBtnKelompok2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PanelKegiatanKelompok2 = new javax.swing.JPanel();
        TabKegiatantBtnKelompok2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PanelPetugasKelompok2 = new javax.swing.JPanel();
        TabPetugastBtnKelompok2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PanelPendonorKelompok2 = new javax.swing.JPanel();
        TabPendonorBtnKelompok2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PanelPasienKelompok2 = new javax.swing.JPanel();
        TabPasienBtnKelompok2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PanelTransfusiKelompok2 = new javax.swing.JPanel();
        TabTransfusiBtnKelompok2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelKeuanganKeluarKelompok2 = new javax.swing.JPanel();
        TabKeuanganKeluarBtnKelompok2 = new javax.swing.JLabel();
        AboutTabbedKelompok2 = new javax.swing.JPanel();
        PanelAboutKelompok2 = new javax.swing.JPanel();
        TabTentangBtnKelompok2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);

        headerKelompok2.setBackground(new java.awt.Color(32, 83, 117));
        headerKelompok2.setPreferredSize(new java.awt.Dimension(800, 50));
        headerKelompok2.setLayout(new java.awt.BorderLayout());

        iconMenu.setBackground(new java.awt.Color(0, 0, 0));
        iconMenu.setPreferredSize(new java.awt.Dimension(150, 50));
        iconMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLogout21552011235.setBackground(new java.awt.Color(32, 83, 117));
        PanelLogout21552011235.setPreferredSize(new java.awt.Dimension(50, 50));
        PanelLogout21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnLogout21552011235.setBackground(new java.awt.Color(30, 23, 15));
        BtnLogout21552011235.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnLogout21552011235.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogout21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnLogout21552011235.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-sign-out-20.png"))); // NOI18N
        BtnLogout21552011235.setText("Logout");
        BtnLogout21552011235.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLogout21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLogout21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLogout21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnLogout21552011235MouseExited(evt);
            }
        });
        PanelLogout21552011235.add(BtnLogout21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 50));

        iconMenu.add(PanelLogout21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 90, -1));

        BtnMax21552011235.setBackground(new java.awt.Color(32, 83, 117));
        BtnMax21552011235.setPreferredSize(new java.awt.Dimension(50, 50));
        BtnMax21552011235.setLayout(new java.awt.BorderLayout());
        iconMenu.add(BtnMax21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        BtnMin21552011235.setBackground(new java.awt.Color(32, 83, 117));
        BtnMin21552011235.setPreferredSize(new java.awt.Dimension(50, 50));
        BtnMin21552011235.setLayout(new java.awt.BorderLayout());
        iconMenu.add(BtnMin21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        headerKelompok2.add(iconMenu, java.awt.BorderLayout.LINE_END);

        getContentPane().add(headerKelompok2, java.awt.BorderLayout.PAGE_START);

        menuKelompok2.setBackground(new java.awt.Color(32, 83, 117));
        menuKelompok2.setPreferredSize(new java.awt.Dimension(270, 450));
        menuKelompok2.setLayout(new java.awt.BorderLayout());

        sidebarKelompok2.setBackground(new java.awt.Color(32, 83, 117));
        sidebarKelompok2.setMinimumSize(new java.awt.Dimension(200, 210));
        sidebarKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePanelKelompok2.setBackground(new java.awt.Color(32, 83, 117));
        homePanelKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePanelKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homePanelKelompok2MouseEntered(evt);
            }
        });
        homePanelKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-home-24.png"))); // NOI18N
        homePanelKelompok2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 43, 50));

        BtnHomeKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnHomeKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        BtnHomeKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnHomeKelompok2.setText("Beranda");
        BtnHomeKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnHomeKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnHomeKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnHomeKelompok2MouseExited(evt);
            }
        });
        homePanelKelompok2.add(BtnHomeKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        sidebarKelompok2.add(homePanelKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 270, 50));

        DataPanelKelompok2.setBackground(new java.awt.Color(32, 83, 117));
        DataPanelKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-doctors-folder-24.png"))); // NOI18N
        DataPanelKelompok2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 43, 50));

        BtnDataKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnDataKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        BtnDataKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnDataKelompok2.setText("Data");
        BtnDataKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDataKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnDataKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnDataKelompok2MouseExited(evt);
            }
        });
        DataPanelKelompok2.add(BtnDataKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        sidebarKelompok2.add(DataPanelKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, -1));

        pagePrintKelompok2.setBackground(new java.awt.Color(32, 83, 117));
        pagePrintKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-print-24.png"))); // NOI18N
        pagePrintKelompok2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 43, 50));

        BtnPrintKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnPrintKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        BtnPrintKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnPrintKelompok2.setText("Halaman Print");
        BtnPrintKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPrintKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnPrintKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnPrintKelompok2MouseExited(evt);
            }
        });
        pagePrintKelompok2.add(BtnPrintKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        sidebarKelompok2.add(pagePrintKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 270, 50));

        aboutPanelKelompok2.setBackground(new java.awt.Color(32, 83, 117));
        aboutPanelKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-info-24.png"))); // NOI18N
        aboutPanelKelompok2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 43, 50));

        BtnAboutKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnAboutKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        BtnAboutKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnAboutKelompok2.setText("Tentang");
        BtnAboutKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAboutKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAboutKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAboutKelompok2MouseExited(evt);
            }
        });
        aboutPanelKelompok2.add(BtnAboutKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        sidebarKelompok2.add(aboutPanelKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 270, 50));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pddm_100px-removebg-preview.png"))); // NOI18N
        sidebarKelompok2.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, 190, 130));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BackLOGO.png"))); // NOI18N
        sidebarKelompok2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 230, 110));

        menuKelompok2.add(sidebarKelompok2, java.awt.BorderLayout.CENTER);

        getContentPane().add(menuKelompok2, java.awt.BorderLayout.LINE_START);

        DashboardviewKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        DashboardviewKelompok2.setLayout(new java.awt.GridLayout(1, 0));

        jTabbedPanelKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        jTabbedPanelKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(64, 49, 33), new java.awt.Color(64, 49, 33), new java.awt.Color(64, 49, 33), new java.awt.Color(64, 49, 33)));
        jTabbedPanelKelompok2.setForeground(new java.awt.Color(17, 43, 60));

        HomeTabbedKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        HomeTabbedKelompok2.setLayout(new java.awt.GridBagLayout());

        IconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-male-user-96.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 280, 0, 0);
        HomeTabbedKelompok2.add(IconUser, gridBagConstraints);

        UserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UserName.setForeground(new java.awt.Color(255, 255, 255));
        UserName.setText("Sekretaris");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(73, 14, 0, 0);
        HomeTabbedKelompok2.add(UserName, gridBagConstraints);

        usernameSekretarisKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameSekretarisKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(73, 14, 0, 0);
        HomeTabbedKelompok2.add(usernameSekretarisKelompok2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Petugas PDDM, dan mencetak setiap laporan.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 198, 143, 92);
        HomeTabbedKelompok2.add(jLabel4, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Anda bisa mengelola data kegiatan donor,");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 223, 0, 0);
        HomeTabbedKelompok2.add(jLabel7, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("___________________");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 314, 0, 0);
        HomeTabbedKelompok2.add(jLabel3, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dashboard Sekretaris");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 262, 0, 0);
        HomeTabbedKelompok2.add(jLabel6, gridBagConstraints);

        jTabbedPanelKelompok2.addTab("", HomeTabbedKelompok2);

        DataTabbedKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        DataTabbedKelompok2.setLayout(new java.awt.GridBagLayout());

        TabHomePanelKegiatan.setBackground(new java.awt.Color(17, 43, 60));
        TabHomePanelKegiatan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        TabHomePanelKegiatan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-activity-history-96.png"))); // NOI18N
        TabHomePanelKegiatan.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 80, 110));

        TabKegiatanKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 37)); // NOI18N
        TabKegiatanKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        TabKegiatanKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabKegiatanKelompok2.setText("Kegiatan");
        TabKegiatanKelompok2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabKegiatanKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabKegiatanKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabKegiatanKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabKegiatanKelompok2MouseExited(evt);
            }
        });
        TabHomePanelKegiatan.add(TabKegiatanKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 220));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(126, 30, 119, 0);
        DataTabbedKelompok2.add(TabHomePanelKegiatan, gridBagConstraints);

        TabPanelPetugasKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        TabPanelPetugasKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        TabPanelPetugasKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-medical-doctor-96.png"))); // NOI18N
        TabPanelPetugasKelompok2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 90, 110));

        TabPetugasKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TabPetugasKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        TabPetugasKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabPetugasKelompok2.setText("Petugas");
        TabPetugasKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabPetugasKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabPetugasKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabPetugasKelompok2MouseExited(evt);
            }
        });
        TabPanelPetugasKelompok2.add(TabPetugasKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 220));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(126, 18, 119, 24);
        DataTabbedKelompok2.add(TabPanelPetugasKelompok2, gridBagConstraints);

        jTabbedPanelKelompok2.addTab("", DataTabbedKelompok2);

        PagePrintTabbedKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        PagePrintTabbedKelompok2.setLayout(new java.awt.GridBagLayout());

        PanelKeuanganMasukKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        PanelKeuanganMasukKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        PanelKeuanganMasukKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabKeuanganMasukBtnKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TabKeuanganMasukBtnKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        TabKeuanganMasukBtnKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabKeuanganMasukBtnKelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-money-48.png"))); // NOI18N
        TabKeuanganMasukBtnKelompok2.setText("Uang Masuk");
        TabKeuanganMasukBtnKelompok2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabKeuanganMasukBtnKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabKeuanganMasukBtnKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabKeuanganMasukBtnKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabKeuanganMasukBtnKelompok2MouseExited(evt);
            }
        });
        PanelKeuanganMasukKelompok2.add(TabKeuanganMasukBtnKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 80));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 20, 0, 0);
        PagePrintTabbedKelompok2.add(PanelKeuanganMasukKelompok2, gridBagConstraints);

        PanelUserKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        PanelUserKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        PanelUserKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabUserBtnKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TabUserBtnKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        TabUserBtnKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabUserBtnKelompok2.setText("User");
        TabUserBtnKelompok2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabUserBtnKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabUserBtnKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabUserBtnKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabUserBtnKelompok2MouseExited(evt);
            }
        });
        PanelUserKelompok2.add(TabUserBtnKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 240));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-male-user-96.png"))); // NOI18N
        PanelUserKelompok2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 19, 55, 0);
        PagePrintTabbedKelompok2.add(PanelUserKelompok2, gridBagConstraints);

        PanelKegiatanKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        PanelKegiatanKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        PanelKegiatanKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabKegiatantBtnKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TabKegiatantBtnKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        TabKegiatantBtnKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabKegiatantBtnKelompok2.setText("Kegiatan");
        TabKegiatantBtnKelompok2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabKegiatantBtnKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabKegiatantBtnKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabKegiatantBtnKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabKegiatantBtnKelompok2MouseExited(evt);
            }
        });
        PanelKegiatanKelompok2.add(TabKegiatantBtnKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 240));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-syringe-96.png"))); // NOI18N
        PanelKegiatanKelompok2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 10, 55, 0);
        PagePrintTabbedKelompok2.add(PanelKegiatanKelompok2, gridBagConstraints);

        PanelPetugasKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        PanelPetugasKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        PanelPetugasKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabPetugastBtnKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TabPetugastBtnKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        TabPetugastBtnKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabPetugastBtnKelompok2.setText("Petugas");
        TabPetugastBtnKelompok2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabPetugastBtnKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabPetugastBtnKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabPetugastBtnKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabPetugastBtnKelompok2MouseExited(evt);
            }
        });
        PanelPetugasKelompok2.add(TabPetugastBtnKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 240));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-medical-doctor-96.png"))); // NOI18N
        PanelPetugasKelompok2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 90));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 10, 55, 0);
        PagePrintTabbedKelompok2.add(PanelPetugasKelompok2, gridBagConstraints);

        PanelPendonorKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        PanelPendonorKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        PanelPendonorKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabPendonorBtnKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TabPendonorBtnKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        TabPendonorBtnKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabPendonorBtnKelompok2.setText("Pendonor");
        TabPendonorBtnKelompok2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabPendonorBtnKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabPendonorBtnKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabPendonorBtnKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabPendonorBtnKelompok2MouseExited(evt);
            }
        });
        PanelPendonorKelompok2.add(TabPendonorBtnKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 240));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-rh+-96.png"))); // NOI18N
        PanelPendonorKelompok2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 9, 55, 0);
        PagePrintTabbedKelompok2.add(PanelPendonorKelompok2, gridBagConstraints);

        PanelPasienKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        PanelPasienKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        PanelPasienKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabPasienBtnKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TabPasienBtnKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        TabPasienBtnKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabPasienBtnKelompok2.setText("Pasien");
        TabPasienBtnKelompok2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabPasienBtnKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabPasienBtnKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabPasienBtnKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabPasienBtnKelompok2MouseExited(evt);
            }
        });
        PanelPasienKelompok2.add(TabPasienBtnKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 240));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-rh--96_1.png"))); // NOI18N
        PanelPasienKelompok2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 10, 55, 0);
        PagePrintTabbedKelompok2.add(PanelPasienKelompok2, gridBagConstraints);

        PanelTransfusiKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        PanelTransfusiKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        PanelTransfusiKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabTransfusiBtnKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TabTransfusiBtnKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        TabTransfusiBtnKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabTransfusiBtnKelompok2.setText("Stok Darah");
        TabTransfusiBtnKelompok2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabTransfusiBtnKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabTransfusiBtnKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabTransfusiBtnKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabTransfusiBtnKelompok2MouseExited(evt);
            }
        });
        PanelTransfusiKelompok2.add(TabTransfusiBtnKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 240));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-heart-with-pulse-96.png"))); // NOI18N
        PanelTransfusiKelompok2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 10, 55, 0);
        PagePrintTabbedKelompok2.add(PanelTransfusiKelompok2, gridBagConstraints);

        PanelKeuanganKeluarKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        PanelKeuanganKeluarKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        PanelKeuanganKeluarKelompok2.setMinimumSize(new java.awt.Dimension(320, 80));
        PanelKeuanganKeluarKelompok2.setPreferredSize(new java.awt.Dimension(320, 80));
        PanelKeuanganKeluarKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabKeuanganKeluarBtnKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TabKeuanganKeluarBtnKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        TabKeuanganKeluarBtnKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabKeuanganKeluarBtnKelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-money-48.png"))); // NOI18N
        TabKeuanganKeluarBtnKelompok2.setText("Uang Keluar");
        TabKeuanganKeluarBtnKelompok2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabKeuanganKeluarBtnKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabKeuanganKeluarBtnKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabKeuanganKeluarBtnKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabKeuanganKeluarBtnKelompok2MouseExited(evt);
            }
        });
        PanelKeuanganKeluarKelompok2.add(TabKeuanganKeluarBtnKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 80));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 10, 0, 10);
        PagePrintTabbedKelompok2.add(PanelKeuanganKeluarKelompok2, gridBagConstraints);

        jTabbedPanelKelompok2.addTab("", PagePrintTabbedKelompok2);

        AboutTabbedKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        AboutTabbedKelompok2.setLayout(new java.awt.GridBagLayout());

        PanelAboutKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        PanelAboutKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        PanelAboutKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabTentangBtnKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        TabTentangBtnKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        TabTentangBtnKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabTentangBtnKelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-info-96.png"))); // NOI18N
        TabTentangBtnKelompok2.setText("Tentang");
        TabTentangBtnKelompok2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabTentangBtnKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabTentangBtnKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabTentangBtnKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabTentangBtnKelompok2MouseExited(evt);
            }
        });
        PanelAboutKelompok2.add(TabTentangBtnKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 200));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(120, 130, 152, 74);
        AboutTabbedKelompok2.add(PanelAboutKelompok2, gridBagConstraints);

        jTabbedPanelKelompok2.addTab("", AboutTabbedKelompok2);

        DashboardviewKelompok2.add(jTabbedPanelKelompok2);

        getContentPane().add(DashboardviewKelompok2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(975, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    public void clickmenu (JPanel h1, JPanel h2, int numberbool){
//        if(numberbool == 1){
//            h1.setBackground(new Color(45,35,23));
//            h2.setBackground(new Color(20,15,10));
//        }else{
//            h1.setBackground(new Color(45,35,23));
//            h2.setBackground(new Color(20,15,10));
//        }
    }
    
    
     public void changeimage(JLabel button, String resourcheimg){
//        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
//        button.setIcon(aimg);
    }
    
    
//    
//    public void hideshow (JPanel menushowhide, boolean dashboard, JLabel button){
//        if (dashboard == true){
//            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
//            changeimage(button, "/iconOutline/icons8-menu-32.png");
//        }else{
//            menushowhide.setPreferredSize(new Dimension(200, menushowhide.getHeight()));
//            changeimage(button, "/iconOutline/icons8-back-32.png");
//        }
//    }
//    
   
    
    
    
    private void homePanelKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelKelompok2MouseEntered
        
    }//GEN-LAST:event_homePanelKelompok2MouseEntered

    private void homePanelKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelKelompok2MouseClicked

    }//GEN-LAST:event_homePanelKelompok2MouseClicked

    private void BtnHomeKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHomeKelompok2MouseEntered
        changecolor(homePanelKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_BtnHomeKelompok2MouseEntered

    private void BtnHomeKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHomeKelompok2MouseExited
        changecolor(homePanelKelompok2, new Color (32,83,117));
    }//GEN-LAST:event_BtnHomeKelompok2MouseExited

    private void BtnDataKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDataKelompok2MouseEntered
       changecolor(DataPanelKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_BtnDataKelompok2MouseEntered

    private void BtnDataKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDataKelompok2MouseExited
        changecolor(DataPanelKelompok2, new Color (32,83,117));
    }//GEN-LAST:event_BtnDataKelompok2MouseExited

    private void BtnAboutKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAboutKelompok2MouseEntered
        changecolor(aboutPanelKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_BtnAboutKelompok2MouseEntered

    private void BtnAboutKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAboutKelompok2MouseExited
        changecolor(aboutPanelKelompok2, new Color (32,83,117));
    }//GEN-LAST:event_BtnAboutKelompok2MouseExited

    private void BtnLogout21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogout21552011235MouseExited
        changecolor(PanelLogout21552011235, new Color (32,83,117));
    }//GEN-LAST:event_BtnLogout21552011235MouseExited

    private void BtnLogout21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogout21552011235MouseEntered
        changecolor(PanelLogout21552011235, new Color (255,24,24));
    }//GEN-LAST:event_BtnLogout21552011235MouseEntered

    private void BtnLogout21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogout21552011235MouseClicked
        new login.loginUser().setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnLogout21552011235MouseClicked

    private void BtnHomeKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHomeKelompok2MouseClicked
       jTabbedPanelKelompok2.setSelectedIndex(0);
    }//GEN-LAST:event_BtnHomeKelompok2MouseClicked

    private void BtnDataKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDataKelompok2MouseClicked
        jTabbedPanelKelompok2.setSelectedIndex(1);
    }//GEN-LAST:event_BtnDataKelompok2MouseClicked

    private void BtnAboutKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAboutKelompok2MouseClicked
        jTabbedPanelKelompok2.setSelectedIndex(3);
    }//GEN-LAST:event_BtnAboutKelompok2MouseClicked

    private void TabTentangBtnKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabTentangBtnKelompok2MouseExited
        changecolor(PanelAboutKelompok2, new Color (17,43,60));
    }//GEN-LAST:event_TabTentangBtnKelompok2MouseExited

    private void TabTentangBtnKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabTentangBtnKelompok2MouseEntered
        changecolor(PanelAboutKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_TabTentangBtnKelompok2MouseEntered

    private void TabTentangBtnKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabTentangBtnKelompok2MouseClicked
        new sekretaris.TentangSekretaris().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabTentangBtnKelompok2MouseClicked

    private void TabKegiatanKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabKegiatanKelompok2MouseExited
        changecolor(TabHomePanelKegiatan, new Color (17,43,60));
    }//GEN-LAST:event_TabKegiatanKelompok2MouseExited

    private void TabKegiatanKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabKegiatanKelompok2MouseEntered
        changecolor(TabHomePanelKegiatan, new Color (32,108,151));
    }//GEN-LAST:event_TabKegiatanKelompok2MouseEntered

    private void TabKegiatanKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabKegiatanKelompok2MouseClicked
        new sekretaris.FormKegiatan().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabKegiatanKelompok2MouseClicked

    private void BtnPrintKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPrintKelompok2MouseExited
        changecolor(pagePrintKelompok2, new Color (32,83,117));
    }//GEN-LAST:event_BtnPrintKelompok2MouseExited

    private void BtnPrintKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPrintKelompok2MouseEntered
        changecolor(pagePrintKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_BtnPrintKelompok2MouseEntered

    private void BtnPrintKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPrintKelompok2MouseClicked
        jTabbedPanelKelompok2.setSelectedIndex(2);
    }//GEN-LAST:event_BtnPrintKelompok2MouseClicked

    private void TabUserBtnKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabUserBtnKelompok2MouseExited
        changecolor(PanelUserKelompok2, new Color (17,43,60));
    }//GEN-LAST:event_TabUserBtnKelompok2MouseExited

    private void TabUserBtnKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabUserBtnKelompok2MouseEntered
        changecolor(PanelUserKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_TabUserBtnKelompok2MouseEntered

    private void TabUserBtnKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabUserBtnKelompok2MouseClicked
        new laporan.PrintUser().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabUserBtnKelompok2MouseClicked

    private void TabKegiatantBtnKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabKegiatantBtnKelompok2MouseClicked
        new laporan.PrintKegiatan().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabKegiatantBtnKelompok2MouseClicked

    private void TabKegiatantBtnKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabKegiatantBtnKelompok2MouseEntered
        changecolor(PanelKegiatanKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_TabKegiatantBtnKelompok2MouseEntered

    private void TabKegiatantBtnKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabKegiatantBtnKelompok2MouseExited
        changecolor(PanelKegiatanKelompok2, new Color (17,43,60));
    }//GEN-LAST:event_TabKegiatantBtnKelompok2MouseExited

    private void TabPetugastBtnKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPetugastBtnKelompok2MouseClicked
        new laporan.PrintPetugas().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabPetugastBtnKelompok2MouseClicked

    private void TabPetugastBtnKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPetugastBtnKelompok2MouseEntered
        changecolor(PanelPetugasKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_TabPetugastBtnKelompok2MouseEntered

    private void TabPetugastBtnKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPetugastBtnKelompok2MouseExited
        changecolor(PanelPetugasKelompok2, new Color (17,43,60));
    }//GEN-LAST:event_TabPetugastBtnKelompok2MouseExited

    private void TabPendonorBtnKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPendonorBtnKelompok2MouseClicked
        new laporan.PrintPendonor().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabPendonorBtnKelompok2MouseClicked

    private void TabPendonorBtnKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPendonorBtnKelompok2MouseEntered
        changecolor(PanelPendonorKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_TabPendonorBtnKelompok2MouseEntered

    private void TabPendonorBtnKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPendonorBtnKelompok2MouseExited
        changecolor(PanelPendonorKelompok2, new Color (17,43,60));
    }//GEN-LAST:event_TabPendonorBtnKelompok2MouseExited

    private void TabPasienBtnKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPasienBtnKelompok2MouseClicked
        new laporan.PrintPasien().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabPasienBtnKelompok2MouseClicked

    private void TabPasienBtnKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPasienBtnKelompok2MouseEntered
        changecolor(PanelPasienKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_TabPasienBtnKelompok2MouseEntered

    private void TabPasienBtnKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPasienBtnKelompok2MouseExited
        changecolor(PanelPasienKelompok2, new Color (17,43,60));
    }//GEN-LAST:event_TabPasienBtnKelompok2MouseExited

    private void TabTransfusiBtnKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabTransfusiBtnKelompok2MouseClicked
        new laporan.PrintStokDarah().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabTransfusiBtnKelompok2MouseClicked

    private void TabTransfusiBtnKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabTransfusiBtnKelompok2MouseEntered
        changecolor(PanelTransfusiKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_TabTransfusiBtnKelompok2MouseEntered

    private void TabTransfusiBtnKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabTransfusiBtnKelompok2MouseExited
        changecolor(PanelTransfusiKelompok2, new Color (17,43,60));
    }//GEN-LAST:event_TabTransfusiBtnKelompok2MouseExited

    private void TabKeuanganMasukBtnKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabKeuanganMasukBtnKelompok2MouseClicked
        new laporan.PrintKeuanganMasuk().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabKeuanganMasukBtnKelompok2MouseClicked

    private void TabKeuanganMasukBtnKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabKeuanganMasukBtnKelompok2MouseEntered
        changecolor(PanelKeuanganMasukKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_TabKeuanganMasukBtnKelompok2MouseEntered

    private void TabKeuanganMasukBtnKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabKeuanganMasukBtnKelompok2MouseExited
        changecolor(PanelKeuanganMasukKelompok2, new Color (17,43,60));
    }//GEN-LAST:event_TabKeuanganMasukBtnKelompok2MouseExited

    private void TabPetugasKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPetugasKelompok2MouseExited
        changecolor(TabPanelPetugasKelompok2, new Color (17,43,60));
    }//GEN-LAST:event_TabPetugasKelompok2MouseExited

    private void TabPetugasKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPetugasKelompok2MouseEntered
        changecolor(TabPanelPetugasKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_TabPetugasKelompok2MouseEntered

    private void TabPetugasKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPetugasKelompok2MouseClicked
        new sekretaris.FormPetugas().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabPetugasKelompok2MouseClicked

    private void TabKeuanganKeluarBtnKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabKeuanganKeluarBtnKelompok2MouseClicked
        new laporan.PrintKeuanganKeluar1().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabKeuanganKeluarBtnKelompok2MouseClicked

    private void TabKeuanganKeluarBtnKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabKeuanganKeluarBtnKelompok2MouseEntered
        changecolor(PanelKeuanganKeluarKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_TabKeuanganKeluarBtnKelompok2MouseEntered

    private void TabKeuanganKeluarBtnKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabKeuanganKeluarBtnKelompok2MouseExited
        changecolor(PanelKeuanganKeluarKelompok2, new Color (17,43,60));
    }//GEN-LAST:event_TabKeuanganKeluarBtnKelompok2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardSekretaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardSekretaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardSekretaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardSekretaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardSekretaris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutTabbedKelompok2;
    private javax.swing.JLabel BtnAboutKelompok2;
    private javax.swing.JLabel BtnDataKelompok2;
    private javax.swing.JLabel BtnHomeKelompok2;
    private javax.swing.JLabel BtnLogout21552011235;
    private javax.swing.JPanel BtnMax21552011235;
    private javax.swing.JPanel BtnMin21552011235;
    private javax.swing.JLabel BtnPrintKelompok2;
    private javax.swing.JPanel DashboardviewKelompok2;
    private javax.swing.JPanel DataPanelKelompok2;
    private javax.swing.JPanel DataTabbedKelompok2;
    private javax.swing.JPanel HomeTabbedKelompok2;
    private javax.swing.JLabel IconUser;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PagePrintTabbedKelompok2;
    private javax.swing.JPanel PanelAboutKelompok2;
    private javax.swing.JPanel PanelKegiatanKelompok2;
    private javax.swing.JPanel PanelKeuanganKeluarKelompok2;
    private javax.swing.JPanel PanelKeuanganMasukKelompok2;
    private javax.swing.JPanel PanelLogout21552011235;
    private javax.swing.JPanel PanelPasienKelompok2;
    private javax.swing.JPanel PanelPendonorKelompok2;
    private javax.swing.JPanel PanelPetugasKelompok2;
    private javax.swing.JPanel PanelTransfusiKelompok2;
    private javax.swing.JPanel PanelUserKelompok2;
    private javax.swing.JPanel TabHomePanelKegiatan;
    private javax.swing.JLabel TabKegiatanKelompok2;
    private javax.swing.JLabel TabKegiatantBtnKelompok2;
    private javax.swing.JLabel TabKeuanganKeluarBtnKelompok2;
    private javax.swing.JLabel TabKeuanganMasukBtnKelompok2;
    private javax.swing.JPanel TabPanelPetugasKelompok2;
    private javax.swing.JLabel TabPasienBtnKelompok2;
    private javax.swing.JLabel TabPendonorBtnKelompok2;
    private javax.swing.JLabel TabPetugasKelompok2;
    private javax.swing.JLabel TabPetugastBtnKelompok2;
    private javax.swing.JLabel TabTentangBtnKelompok2;
    private javax.swing.JLabel TabTransfusiBtnKelompok2;
    private javax.swing.JLabel TabUserBtnKelompok2;
    private javax.swing.JLabel UserName;
    private javax.swing.JPanel aboutPanelKelompok2;
    private javax.swing.JPanel headerKelompok2;
    private javax.swing.JPanel homePanelKelompok2;
    private javax.swing.JPanel iconMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPanelKelompok2;
    private javax.swing.JPanel menuKelompok2;
    private javax.swing.JPanel pagePrintKelompok2;
    private javax.swing.JPanel sidebarKelompok2;
    public static final javax.swing.JLabel usernameSekretarisKelompok2 = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

    private static class color {

        public color() {
        }
    }

    private static class Jpanel {

        public Jpanel() {
        }

        private void setbackground(color rand) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

    private static class jTabbedPanel {

        public jTabbedPanel() {
        }
    }
}
