/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author albi mudakar
 */
public class dashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    boolean a= true;
    public dashboardAdmin() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        header21552011235 = new javax.swing.JPanel();
        iconMenu = new javax.swing.JPanel();
        PanelLogout21552011235 = new javax.swing.JPanel();
        BtnLogout21552011235 = new javax.swing.JLabel();
        BtnMax21552011235 = new javax.swing.JPanel();
        BtnMin21552011235 = new javax.swing.JPanel();
        menu21552011235 = new javax.swing.JPanel();
        sidebar21552011235 = new javax.swing.JPanel();
        homePanel21552011235 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnHome21552011235 = new javax.swing.JLabel();
        daftarMenuPanel21552011235 = new javax.swing.JPanel();
        BtnData21552011235 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        riwayatPanel21552011235 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BtnLaporan21552011235 = new javax.swing.JLabel();
        tentangPanel21552011235 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        BtnTentang21552011235 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Dashboardview21552011235 = new javax.swing.JPanel();
        jTabbedPanel21552011235 = new javax.swing.JTabbedPane();
        HomeTabbed21552011235 = new javax.swing.JPanel();
        IconUser = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        TabHomePanelData21552011235 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TabHomeBtnData21552011235 = new javax.swing.JLabel();
        TabHomePanelRiwayat21552011235 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        TabHomeBtnRiwayat21552011235 = new javax.swing.JLabel();
        TabHomePanelTentang21552011235 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        TabHomeBtnTentang21552011235 = new javax.swing.JLabel();
        DataTabbed21552011235 = new javax.swing.JPanel();
        PanelDataBarista21552011235 = new javax.swing.JPanel();
        TabDataBarista21552011235 = new javax.swing.JLabel();
        PanelDatamenu21552011235 = new javax.swing.JPanel();
        TabDataMenuBtn21552011235 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RiwayatTabbed21552011235 = new javax.swing.JPanel();
        PanelRiwayat21552011235 = new javax.swing.JPanel();
        TabRiwayatBtn21552011235 = new javax.swing.JLabel();
        TentangTabbed21552011235 = new javax.swing.JPanel();
        PanelTentang21552011235 = new javax.swing.JPanel();
        TabTentangBtn21552011235 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);

        header21552011235.setBackground(new java.awt.Color(30, 23, 15));
        header21552011235.setPreferredSize(new java.awt.Dimension(800, 50));
        header21552011235.setLayout(new java.awt.BorderLayout());

        iconMenu.setBackground(new java.awt.Color(0, 0, 0));
        iconMenu.setPreferredSize(new java.awt.Dimension(150, 50));
        iconMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLogout21552011235.setBackground(new java.awt.Color(30, 23, 15));
        PanelLogout21552011235.setPreferredSize(new java.awt.Dimension(50, 50));
        PanelLogout21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnLogout21552011235.setBackground(new java.awt.Color(30, 23, 15));
        BtnLogout21552011235.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnLogout21552011235.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogout21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnLogout21552011235.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-sign-out-20.png"))); // NOI18N
        BtnLogout21552011235.setText("Logout");
        BtnLogout21552011235.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLogout21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLogout21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLogout21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnLogout21552011235MouseExited(evt);
            }
        });
        PanelLogout21552011235.add(BtnLogout21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 50));

        iconMenu.add(PanelLogout21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 90, -1));

        BtnMax21552011235.setBackground(new java.awt.Color(30, 23, 15));
        BtnMax21552011235.setPreferredSize(new java.awt.Dimension(50, 50));
        BtnMax21552011235.setLayout(new java.awt.BorderLayout());
        iconMenu.add(BtnMax21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        BtnMin21552011235.setBackground(new java.awt.Color(30, 23, 15));
        BtnMin21552011235.setPreferredSize(new java.awt.Dimension(50, 50));
        BtnMin21552011235.setLayout(new java.awt.BorderLayout());
        iconMenu.add(BtnMin21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        header21552011235.add(iconMenu, java.awt.BorderLayout.LINE_END);

        getContentPane().add(header21552011235, java.awt.BorderLayout.PAGE_START);

        menu21552011235.setPreferredSize(new java.awt.Dimension(270, 450));
        menu21552011235.setLayout(new java.awt.BorderLayout());

        sidebar21552011235.setBackground(new java.awt.Color(45, 35, 23));
        sidebar21552011235.setMinimumSize(new java.awt.Dimension(200, 210));
        sidebar21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePanel21552011235.setBackground(new java.awt.Color(45, 35, 23));
        homePanel21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePanel21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homePanel21552011235MouseEntered(evt);
            }
        });
        homePanel21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-home-20.png"))); // NOI18N
        homePanel21552011235.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 43, 50));

        BtnHome21552011235.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnHome21552011235.setForeground(new java.awt.Color(255, 255, 255));
        BtnHome21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnHome21552011235.setText("Home");
        BtnHome21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnHome21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnHome21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnHome21552011235MouseExited(evt);
            }
        });
        homePanel21552011235.add(BtnHome21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        sidebar21552011235.add(homePanel21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 270, 50));

        daftarMenuPanel21552011235.setBackground(new java.awt.Color(45, 35, 23));
        daftarMenuPanel21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnData21552011235.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnData21552011235.setForeground(new java.awt.Color(255, 255, 255));
        BtnData21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnData21552011235.setText("Data");
        BtnData21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnData21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnData21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnData21552011235MouseExited(evt);
            }
        });
        daftarMenuPanel21552011235.add(BtnData21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-coffee-to-go-20.png"))); // NOI18N
        daftarMenuPanel21552011235.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 43, 50));

        sidebar21552011235.add(daftarMenuPanel21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, -1));

        riwayatPanel21552011235.setBackground(new java.awt.Color(45, 35, 23));
        riwayatPanel21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-activity-feed-20.png"))); // NOI18N
        riwayatPanel21552011235.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 43, 50));

        BtnLaporan21552011235.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnLaporan21552011235.setForeground(new java.awt.Color(255, 255, 255));
        BtnLaporan21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnLaporan21552011235.setText("Laporan Riwayat");
        BtnLaporan21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLaporan21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLaporan21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnLaporan21552011235MouseExited(evt);
            }
        });
        riwayatPanel21552011235.add(BtnLaporan21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        sidebar21552011235.add(riwayatPanel21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 270, 50));

        tentangPanel21552011235.setBackground(new java.awt.Color(45, 35, 23));
        tentangPanel21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-info-20.png"))); // NOI18N
        tentangPanel21552011235.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 43, 50));

        BtnTentang21552011235.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnTentang21552011235.setForeground(new java.awt.Color(255, 255, 255));
        BtnTentang21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnTentang21552011235.setText("Tentang");
        BtnTentang21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnTentang21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnTentang21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnTentang21552011235MouseExited(evt);
            }
        });
        tentangPanel21552011235.add(BtnTentang21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        sidebar21552011235.add(tentangPanel21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 270, 50));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/langkop120px.png"))); // NOI18N
        sidebar21552011235.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 100));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/beansHorizonUp.png"))); // NOI18N
        sidebar21552011235.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 270, 170));

        menu21552011235.add(sidebar21552011235, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu21552011235, java.awt.BorderLayout.LINE_START);

        Dashboardview21552011235.setBackground(new java.awt.Color(64, 49, 33));
        Dashboardview21552011235.setLayout(new java.awt.GridLayout(1, 0));

        jTabbedPanel21552011235.setBackground(new java.awt.Color(64, 49, 33));
        jTabbedPanel21552011235.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(64, 49, 33), new java.awt.Color(64, 49, 33), new java.awt.Color(64, 49, 33), new java.awt.Color(64, 49, 33)));
        jTabbedPanel21552011235.setForeground(new java.awt.Color(64, 49, 33));

        HomeTabbed21552011235.setBackground(new java.awt.Color(64, 49, 33));
        HomeTabbed21552011235.setLayout(new java.awt.GridBagLayout());

        IconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-male-user-96.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 34, 0, 0);
        HomeTabbed21552011235.add(IconUser, gridBagConstraints);

        UserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UserName.setForeground(new java.awt.Color(255, 255, 255));
        UserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UserName.setText("Admin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 4, 0, 0);
        HomeTabbed21552011235.add(UserName, gridBagConstraints);

        TabHomePanelData21552011235.setBackground(new java.awt.Color(64, 49, 33));
        TabHomePanelData21552011235.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        TabHomePanelData21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-coffee-to-go-96.png"))); // NOI18N
        TabHomePanelData21552011235.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 60, -1));

        TabHomeBtnData21552011235.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TabHomeBtnData21552011235.setForeground(new java.awt.Color(255, 255, 255));
        TabHomeBtnData21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabHomeBtnData21552011235.setText("Data");
        TabHomeBtnData21552011235.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabHomeBtnData21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabHomeBtnData21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabHomeBtnData21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabHomeBtnData21552011235MouseExited(evt);
            }
        });
        TabHomePanelData21552011235.add(TabHomeBtnData21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 170));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = -4;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 130, 101, 0);
        HomeTabbed21552011235.add(TabHomePanelData21552011235, gridBagConstraints);

        TabHomePanelRiwayat21552011235.setBackground(new java.awt.Color(64, 49, 33));
        TabHomePanelRiwayat21552011235.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        TabHomePanelRiwayat21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-activity-feed-96.png"))); // NOI18N
        TabHomePanelRiwayat21552011235.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 100, 100));

        TabHomeBtnRiwayat21552011235.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TabHomeBtnRiwayat21552011235.setForeground(new java.awt.Color(255, 255, 255));
        TabHomeBtnRiwayat21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabHomeBtnRiwayat21552011235.setText("Laporan");
        TabHomeBtnRiwayat21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabHomeBtnRiwayat21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabHomeBtnRiwayat21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabHomeBtnRiwayat21552011235MouseExited(evt);
            }
        });
        TabHomePanelRiwayat21552011235.add(TabHomeBtnRiwayat21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 170));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = -4;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 64, 101, 0);
        HomeTabbed21552011235.add(TabHomePanelRiwayat21552011235, gridBagConstraints);

        TabHomePanelTentang21552011235.setBackground(new java.awt.Color(64, 49, 33));
        TabHomePanelTentang21552011235.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        TabHomePanelTentang21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-info-96.png"))); // NOI18N
        TabHomePanelTentang21552011235.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -16, 87, 90));

        TabHomeBtnTentang21552011235.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TabHomeBtnTentang21552011235.setForeground(new java.awt.Color(255, 255, 255));
        TabHomeBtnTentang21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabHomeBtnTentang21552011235.setText("Tentang");
        TabHomeBtnTentang21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabHomeBtnTentang21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabHomeBtnTentang21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabHomeBtnTentang21552011235MouseExited(evt);
            }
        });
        TabHomePanelTentang21552011235.add(TabHomeBtnTentang21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 170));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = -4;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 0, 101, 0);
        HomeTabbed21552011235.add(TabHomePanelTentang21552011235, gridBagConstraints);

        userName.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 4, 0, 100);
        HomeTabbed21552011235.add(userName, gridBagConstraints);

        jTabbedPanel21552011235.addTab("", HomeTabbed21552011235);

        DataTabbed21552011235.setBackground(new java.awt.Color(64, 49, 33));
        DataTabbed21552011235.setLayout(new java.awt.GridBagLayout());

        PanelDataBarista21552011235.setBackground(new java.awt.Color(64, 49, 33));
        PanelDataBarista21552011235.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        PanelDataBarista21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabDataBarista21552011235.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        TabDataBarista21552011235.setForeground(new java.awt.Color(255, 255, 255));
        TabDataBarista21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabDataBarista21552011235.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-male-user-48.png"))); // NOI18N
        TabDataBarista21552011235.setText("Data Barista");
        TabDataBarista21552011235.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabDataBarista21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabDataBarista21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabDataBarista21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabDataBarista21552011235MouseExited(evt);
            }
        });
        PanelDataBarista21552011235.add(TabDataBarista21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 160));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 20, 138, 10);
        DataTabbed21552011235.add(PanelDataBarista21552011235, gridBagConstraints);

        PanelDatamenu21552011235.setBackground(new java.awt.Color(64, 49, 33));
        PanelDatamenu21552011235.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        PanelDatamenu21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabDataMenuBtn21552011235.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        TabDataMenuBtn21552011235.setForeground(new java.awt.Color(255, 255, 255));
        TabDataMenuBtn21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabDataMenuBtn21552011235.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-coffee-to-go-48.png"))); // NOI18N
        TabDataMenuBtn21552011235.setText("Data Menu");
        TabDataMenuBtn21552011235.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabDataMenuBtn21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabDataMenuBtn21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabDataMenuBtn21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabDataMenuBtn21552011235MouseExited(evt);
            }
        });
        PanelDatamenu21552011235.add(TabDataMenuBtn21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 160));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 20, 138, 0);
        DataTabbed21552011235.add(PanelDatamenu21552011235, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Data");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 164;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 240, 0, 0);
        DataTabbed21552011235.add(jLabel2, gridBagConstraints);

        jTabbedPanel21552011235.addTab("", DataTabbed21552011235);

        RiwayatTabbed21552011235.setBackground(new java.awt.Color(64, 49, 33));
        RiwayatTabbed21552011235.setLayout(new java.awt.GridBagLayout());

        PanelRiwayat21552011235.setBackground(new java.awt.Color(64, 49, 33));
        PanelRiwayat21552011235.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        PanelRiwayat21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabRiwayatBtn21552011235.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        TabRiwayatBtn21552011235.setForeground(new java.awt.Color(255, 255, 255));
        TabRiwayatBtn21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabRiwayatBtn21552011235.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-activity-feed-96.png"))); // NOI18N
        TabRiwayatBtn21552011235.setText("Laporan Riwayat");
        TabRiwayatBtn21552011235.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabRiwayatBtn21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabRiwayatBtn21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabRiwayatBtn21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabRiwayatBtn21552011235MouseExited(evt);
            }
        });
        PanelRiwayat21552011235.add(TabRiwayatBtn21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 200));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(120, 130, 152, 74);
        RiwayatTabbed21552011235.add(PanelRiwayat21552011235, gridBagConstraints);

        jTabbedPanel21552011235.addTab("", RiwayatTabbed21552011235);

        TentangTabbed21552011235.setBackground(new java.awt.Color(64, 49, 33));
        TentangTabbed21552011235.setLayout(new java.awt.GridBagLayout());

        PanelTentang21552011235.setBackground(new java.awt.Color(64, 49, 33));
        PanelTentang21552011235.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        PanelTentang21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabTentangBtn21552011235.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        TabTentangBtn21552011235.setForeground(new java.awt.Color(255, 255, 255));
        TabTentangBtn21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabTentangBtn21552011235.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-info-96.png"))); // NOI18N
        TabTentangBtn21552011235.setText("Tentang");
        TabTentangBtn21552011235.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabTentangBtn21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabTentangBtn21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabTentangBtn21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabTentangBtn21552011235MouseExited(evt);
            }
        });
        PanelTentang21552011235.add(TabTentangBtn21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 200));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(120, 130, 152, 74);
        TentangTabbed21552011235.add(PanelTentang21552011235, gridBagConstraints);

        jTabbedPanel21552011235.addTab("", TentangTabbed21552011235);

        Dashboardview21552011235.add(jTabbedPanel21552011235);

        getContentPane().add(Dashboardview21552011235, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(975, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    public void clickmenu (JPanel h1, JPanel h2, int numberbool){
//        if(numberbool == 1){
//            h1.setBackground(new Color(45,35,23));
//            h2.setBackground(new Color(20,15,10));
//        }else{
//            h1.setBackground(new Color(45,35,23));
//            h2.setBackground(new Color(20,15,10));
//        }
    }
    
    
     public void changeimage(JLabel button, String resourcheimg){
//        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
//        button.setIcon(aimg);
    }
    
    
//    
//    public void hideshow (JPanel menushowhide, boolean dashboard, JLabel button){
//        if (dashboard == true){
//            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
//            changeimage(button, "/iconOutline/icons8-menu-32.png");
//        }else{
//            menushowhide.setPreferredSize(new Dimension(200, menushowhide.getHeight()));
//            changeimage(button, "/iconOutline/icons8-back-32.png");
//        }
//    }
//    
   
    
    
    
    private void homePanel21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanel21552011235MouseEntered
        
    }//GEN-LAST:event_homePanel21552011235MouseEntered

    private void homePanel21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanel21552011235MouseClicked

    }//GEN-LAST:event_homePanel21552011235MouseClicked

    private void BtnHome21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHome21552011235MouseEntered
        changecolor(homePanel21552011235, new Color (72,59,43));
    }//GEN-LAST:event_BtnHome21552011235MouseEntered

    private void BtnHome21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHome21552011235MouseExited
        changecolor(homePanel21552011235, new Color (45,35,23));
    }//GEN-LAST:event_BtnHome21552011235MouseExited

    private void BtnLaporan21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLaporan21552011235MouseEntered
        changecolor(riwayatPanel21552011235, new Color (72,59,43));
    }//GEN-LAST:event_BtnLaporan21552011235MouseEntered

    private void BtnLaporan21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLaporan21552011235MouseExited
        changecolor(riwayatPanel21552011235, new Color (45,35,23));
    }//GEN-LAST:event_BtnLaporan21552011235MouseExited

    private void BtnData21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnData21552011235MouseEntered
       changecolor(daftarMenuPanel21552011235, new Color (72,59,43));
    }//GEN-LAST:event_BtnData21552011235MouseEntered

    private void BtnData21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnData21552011235MouseExited
        changecolor(daftarMenuPanel21552011235, new Color (45,35,23));
    }//GEN-LAST:event_BtnData21552011235MouseExited

    private void BtnTentang21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTentang21552011235MouseEntered
        changecolor(tentangPanel21552011235, new Color (72,59,43));
    }//GEN-LAST:event_BtnTentang21552011235MouseEntered

    private void BtnTentang21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTentang21552011235MouseExited
        changecolor(tentangPanel21552011235, new Color (45,35,23));
    }//GEN-LAST:event_BtnTentang21552011235MouseExited

    private void BtnLogout21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogout21552011235MouseExited
        changecolor(PanelLogout21552011235, new Color (20,15,10));
    }//GEN-LAST:event_BtnLogout21552011235MouseExited

    private void BtnLogout21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogout21552011235MouseEntered
        changecolor(PanelLogout21552011235, new Color (255,24,24));
    }//GEN-LAST:event_BtnLogout21552011235MouseEntered

    private void BtnLogout21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogout21552011235MouseClicked
        new login.selamatDatang().setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnLogout21552011235MouseClicked

    private void BtnHome21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHome21552011235MouseClicked
       jTabbedPanel21552011235.setSelectedIndex(0);
    }//GEN-LAST:event_BtnHome21552011235MouseClicked

    private void BtnData21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnData21552011235MouseClicked
        jTabbedPanel21552011235.setSelectedIndex(1);
    }//GEN-LAST:event_BtnData21552011235MouseClicked

    private void BtnLaporan21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLaporan21552011235MouseClicked
        jTabbedPanel21552011235.setSelectedIndex(2);
    }//GEN-LAST:event_BtnLaporan21552011235MouseClicked

    private void BtnTentang21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTentang21552011235MouseClicked
        jTabbedPanel21552011235.setSelectedIndex(3);
    }//GEN-LAST:event_BtnTentang21552011235MouseClicked

    private void TabTentangBtn21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabTentangBtn21552011235MouseExited
        changecolor(PanelTentang21552011235, new Color (64,49,33));
    }//GEN-LAST:event_TabTentangBtn21552011235MouseExited

    private void TabTentangBtn21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabTentangBtn21552011235MouseEntered
        changecolor(PanelTentang21552011235, new Color (45,35,23));
    }//GEN-LAST:event_TabTentangBtn21552011235MouseEntered

    private void TabTentangBtn21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabTentangBtn21552011235MouseClicked
        new admin.tentangAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabTentangBtn21552011235MouseClicked

    private void TabRiwayatBtn21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabRiwayatBtn21552011235MouseExited
        changecolor(PanelRiwayat21552011235, new Color (64,49,33));
    }//GEN-LAST:event_TabRiwayatBtn21552011235MouseExited

    private void TabRiwayatBtn21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabRiwayatBtn21552011235MouseEntered
        changecolor(PanelRiwayat21552011235, new Color (45,35,23));
    }//GEN-LAST:event_TabRiwayatBtn21552011235MouseEntered

    private void TabRiwayatBtn21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabRiwayatBtn21552011235MouseClicked
        new laporan.LaporanRiwayat().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabRiwayatBtn21552011235MouseClicked

    private void TabDataMenuBtn21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabDataMenuBtn21552011235MouseExited
        changecolor(PanelDatamenu21552011235, new Color (64,49,33));
    }//GEN-LAST:event_TabDataMenuBtn21552011235MouseExited

    private void TabDataMenuBtn21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabDataMenuBtn21552011235MouseEntered
        changecolor(PanelDatamenu21552011235, new Color (45,35,23));
    }//GEN-LAST:event_TabDataMenuBtn21552011235MouseEntered

    private void TabDataMenuBtn21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabDataMenuBtn21552011235MouseClicked
        new admin.dataMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabDataMenuBtn21552011235MouseClicked

    private void TabDataBarista21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabDataBarista21552011235MouseExited
        changecolor(PanelDataBarista21552011235, new Color (64,49,33));
    }//GEN-LAST:event_TabDataBarista21552011235MouseExited

    private void TabDataBarista21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabDataBarista21552011235MouseEntered
        changecolor(PanelDataBarista21552011235, new Color (45,35,23));
    }//GEN-LAST:event_TabDataBarista21552011235MouseEntered

    private void TabDataBarista21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabDataBarista21552011235MouseClicked
        new admin.akunBarista().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabDataBarista21552011235MouseClicked

    private void TabHomeBtnTentang21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabHomeBtnTentang21552011235MouseExited
        changecolor(TabHomePanelTentang21552011235, new Color (64,49,33));
    }//GEN-LAST:event_TabHomeBtnTentang21552011235MouseExited

    private void TabHomeBtnTentang21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabHomeBtnTentang21552011235MouseEntered
        changecolor(TabHomePanelTentang21552011235, new Color (45,35,23));
    }//GEN-LAST:event_TabHomeBtnTentang21552011235MouseEntered

    private void TabHomeBtnTentang21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabHomeBtnTentang21552011235MouseClicked
        jTabbedPanel21552011235.setSelectedIndex(3);
    }//GEN-LAST:event_TabHomeBtnTentang21552011235MouseClicked

    private void TabHomeBtnRiwayat21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabHomeBtnRiwayat21552011235MouseExited
        changecolor(TabHomePanelRiwayat21552011235, new Color (64,49,33));
    }//GEN-LAST:event_TabHomeBtnRiwayat21552011235MouseExited

    private void TabHomeBtnRiwayat21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabHomeBtnRiwayat21552011235MouseEntered
        changecolor(TabHomePanelRiwayat21552011235, new Color (45,35,23));
    }//GEN-LAST:event_TabHomeBtnRiwayat21552011235MouseEntered

    private void TabHomeBtnRiwayat21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabHomeBtnRiwayat21552011235MouseClicked
        jTabbedPanel21552011235.setSelectedIndex(2);
    }//GEN-LAST:event_TabHomeBtnRiwayat21552011235MouseClicked

    private void TabHomeBtnData21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabHomeBtnData21552011235MouseExited
        changecolor(TabHomePanelData21552011235, new Color (64,49,33));
    }//GEN-LAST:event_TabHomeBtnData21552011235MouseExited

    private void TabHomeBtnData21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabHomeBtnData21552011235MouseEntered
        changecolor(TabHomePanelData21552011235, new Color (45,35,23));
    }//GEN-LAST:event_TabHomeBtnData21552011235MouseEntered

    private void TabHomeBtnData21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabHomeBtnData21552011235MouseClicked
        jTabbedPanel21552011235.setSelectedIndex(1);
    }//GEN-LAST:event_TabHomeBtnData21552011235MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnData21552011235;
    private javax.swing.JLabel BtnHome21552011235;
    private javax.swing.JLabel BtnLaporan21552011235;
    private javax.swing.JLabel BtnLogout21552011235;
    private javax.swing.JPanel BtnMax21552011235;
    private javax.swing.JPanel BtnMin21552011235;
    private javax.swing.JLabel BtnTentang21552011235;
    private javax.swing.JPanel Dashboardview21552011235;
    private javax.swing.JPanel DataTabbed21552011235;
    private javax.swing.JPanel HomeTabbed21552011235;
    private javax.swing.JLabel IconUser;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PanelDataBarista21552011235;
    private javax.swing.JPanel PanelDatamenu21552011235;
    private javax.swing.JPanel PanelLogout21552011235;
    private javax.swing.JPanel PanelRiwayat21552011235;
    private javax.swing.JPanel PanelTentang21552011235;
    private javax.swing.JPanel RiwayatTabbed21552011235;
    private javax.swing.JLabel TabDataBarista21552011235;
    private javax.swing.JLabel TabDataMenuBtn21552011235;
    private javax.swing.JLabel TabHomeBtnData21552011235;
    private javax.swing.JLabel TabHomeBtnRiwayat21552011235;
    private javax.swing.JLabel TabHomeBtnTentang21552011235;
    private javax.swing.JPanel TabHomePanelData21552011235;
    private javax.swing.JPanel TabHomePanelRiwayat21552011235;
    private javax.swing.JPanel TabHomePanelTentang21552011235;
    private javax.swing.JLabel TabRiwayatBtn21552011235;
    private javax.swing.JLabel TabTentangBtn21552011235;
    private javax.swing.JPanel TentangTabbed21552011235;
    private javax.swing.JLabel UserName;
    private javax.swing.JPanel daftarMenuPanel21552011235;
    private javax.swing.JPanel header21552011235;
    private javax.swing.JPanel homePanel21552011235;
    private javax.swing.JPanel iconMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPanel21552011235;
    private javax.swing.JPanel menu21552011235;
    private javax.swing.JPanel riwayatPanel21552011235;
    private javax.swing.JPanel sidebar21552011235;
    private javax.swing.JPanel tentangPanel21552011235;
    public static final javax.swing.JLabel userName = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

    private static class color {

        public color() {
        }
    }

    private static class Jpanel {

        public Jpanel() {
        }

        private void setbackground(color rand) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

    private static class jTabbedPanel {

        public jTabbedPanel() {
        }
    }
}
