/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import transaksi.*;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author albin
 */
public class tentangAdmin extends javax.swing.JFrame {

    /**
     * Creates new form daftarMenu
     */
    public tentangAdmin() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        PanelBack21552011235 = new javax.swing.JPanel();
        BtnBack21552011235 = new javax.swing.JLabel();
        DaftarMenu2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Navbar1 = new javax.swing.JPanel();
        PanelBack77174756 = new javax.swing.JPanel();
        BtnBack77174756 = new javax.swing.JLabel();
        DaftarMenu1 = new javax.swing.JLabel();
        line6 = new javax.swing.JLabel();
        DaftarMenu = new javax.swing.JLabel();
        DaftarMenu3 = new javax.swing.JLabel();
        DaftarMenu6 = new javax.swing.JLabel();
        DaftarMenu7 = new javax.swing.JLabel();
        DaftarMenu8 = new javax.swing.JLabel();
        DaftarMenu4 = new javax.swing.JLabel();
        line7 = new javax.swing.JLabel();
        DaftarMenu5 = new javax.swing.JLabel();
        DaftarMenu9 = new javax.swing.JLabel();
        DaftarMenu10 = new javax.swing.JLabel();
        DaftarMenu11 = new javax.swing.JLabel();
        DaftarMenu12 = new javax.swing.JLabel();
        line8 = new javax.swing.JLabel();
        DaftarMenu13 = new javax.swing.JLabel();
        DaftarMenu14 = new javax.swing.JLabel();
        DaftarMenu15 = new javax.swing.JLabel();
        DaftarMenu16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(64, 49, 33));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Navbar.setBackground(new java.awt.Color(45, 35, 23));
        Navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBack21552011235.setBackground(new java.awt.Color(45, 35, 23));
        PanelBack21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnBack21552011235.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnBack21552011235.setForeground(new java.awt.Color(255, 255, 255));
        BtnBack21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnBack21552011235.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-back-48.png"))); // NOI18N
        BtnBack21552011235.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBack21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBack21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnBack21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnBack21552011235MouseExited(evt);
            }
        });
        PanelBack21552011235.add(BtnBack21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 60));

        Navbar.add(PanelBack21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 60));

        DaftarMenu2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        DaftarMenu2.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaftarMenu2.setText("Tentang");
        Navbar.add(DaftarMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 280, 60));

        jPanel2.add(Navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 60));

        jPanel3.setBackground(new java.awt.Color(64, 49, 33));
        jPanel3.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Navbar1.setBackground(new java.awt.Color(45, 35, 23));
        Navbar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBack77174756.setBackground(new java.awt.Color(45, 35, 23));
        PanelBack77174756.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnBack77174756.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnBack77174756.setForeground(new java.awt.Color(255, 255, 255));
        BtnBack77174756.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnBack77174756.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-back-48.png"))); // NOI18N
        BtnBack77174756.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBack77174756MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnBack77174756MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnBack77174756MouseExited(evt);
            }
        });
        PanelBack77174756.add(BtnBack77174756, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 60));

        Navbar1.add(PanelBack77174756, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 60));

        DaftarMenu1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        DaftarMenu1.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaftarMenu1.setText("Transaksi");
        Navbar1.add(DaftarMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 280, 60));

        jPanel3.add(Navbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 60));

        line6.setBackground(new java.awt.Color(255, 255, 255));
        line6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        line6.setForeground(new java.awt.Color(255, 255, 255));
        line6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        line6.setText("____________________________");
        jPanel3.add(line6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 270, 20));

        DaftarMenu.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        DaftarMenu.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaftarMenu.setText("Sekolah Tinggi Teknologi Bandung. ");
        jPanel3.add(DaftarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, 560, 40));

        DaftarMenu3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DaftarMenu3.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaftarMenu3.setText("Akses Role Admin");
        jPanel3.add(DaftarMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 190, 60));

        DaftarMenu6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        DaftarMenu6.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DaftarMenu6.setText("1. Menambahkan, edit dan hapus  Data Menu.");
        jPanel3.add(DaftarMenu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 320, 40));

        DaftarMenu7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        DaftarMenu7.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DaftarMenu7.setText("3. Print Laporan Riwayat Transaksi.");
        jPanel3.add(DaftarMenu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 270, 40));

        DaftarMenu8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        DaftarMenu8.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DaftarMenu8.setText("2. Menambah, edit dan hapus Data Barista.");
        jPanel3.add(DaftarMenu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 290, 40));

        DaftarMenu4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DaftarMenu4.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaftarMenu4.setText("Aplikasi");
        jPanel3.add(DaftarMenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 190, 60));

        line7.setBackground(new java.awt.Color(255, 255, 255));
        line7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        line7.setForeground(new java.awt.Color(255, 255, 255));
        line7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        line7.setText("____________________________");
        jPanel3.add(line7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 270, 20));

        DaftarMenu5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        DaftarMenu5.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DaftarMenu5.setText("5. Print Data menu, Data Barista, Laporan Transaksi dan Riwayat.");
        jPanel3.add(DaftarMenu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 460, 40));

        DaftarMenu9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        DaftarMenu9.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaftarMenu9.setText("Aplikasi Sistem Transaksi penjualan Langkah Kopi merupakan sebuah aplikasi  ");
        jPanel3.add(DaftarMenu9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 530, 40));

        DaftarMenu10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        DaftarMenu10.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaftarMenu10.setText("yang di rancang untuk bertransaksi pembelian dan mengelola keuangan");
        jPanel3.add(DaftarMenu10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 500, 40));

        DaftarMenu11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        DaftarMenu11.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaftarMenu11.setText("melalui feature laporan dan riwayat transaksi. ");
        jPanel3.add(DaftarMenu11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 310, 40));

        DaftarMenu12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DaftarMenu12.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaftarMenu12.setText("Developer");
        jPanel3.add(DaftarMenu12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, 190, 60));

        line8.setBackground(new java.awt.Color(255, 255, 255));
        line8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        line8.setForeground(new java.awt.Color(255, 255, 255));
        line8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        line8.setText("____________________________");
        jPanel3.add(line8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 270, 20));

        DaftarMenu13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        DaftarMenu13.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaftarMenu13.setText("Versi Aplikasi 1.0");
        jPanel3.add(DaftarMenu13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 150, 40));

        DaftarMenu14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        DaftarMenu14.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaftarMenu14.setText("Aplikasi ini dibangun oleh seorang mahasiswa yang bernama Albi Mudakar Nasyabi");
        jPanel3.add(DaftarMenu14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 560, 40));

        DaftarMenu15.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        DaftarMenu15.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaftarMenu15.setText("untuk menempuh Ujian Tengah Semester Algoritma dan pemrograman II.");
        jPanel3.add(DaftarMenu15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 610, 560, 40));

        DaftarMenu16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        DaftarMenu16.setForeground(new java.awt.Color(255, 255, 255));
        DaftarMenu16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DaftarMenu16.setText("4. Monitoring Riwayat Transaksi.");
        jPanel3.add(DaftarMenu16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 270, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1382, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBack21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBack21552011235MouseClicked
        new admin.dashboardAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnBack21552011235MouseClicked

    private void BtnBack21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBack21552011235MouseEntered
        changecolor(PanelBack21552011235, new Color (255,24,24));
    }//GEN-LAST:event_BtnBack21552011235MouseEntered

    private void BtnBack21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBack21552011235MouseExited
        changecolor(PanelBack21552011235, new Color (45,35,23));
    }//GEN-LAST:event_BtnBack21552011235MouseExited

    private void BtnBack77174756MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBack77174756MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBack77174756MouseExited

    private void BtnBack77174756MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBack77174756MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBack77174756MouseEntered

    private void BtnBack77174756MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBack77174756MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBack77174756MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tentangAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tentangAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tentangAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tentangAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tentangAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnBack21552011235;
    private javax.swing.JLabel BtnBack77174756;
    private javax.swing.JLabel DaftarMenu;
    private javax.swing.JLabel DaftarMenu1;
    private javax.swing.JLabel DaftarMenu10;
    private javax.swing.JLabel DaftarMenu11;
    private javax.swing.JLabel DaftarMenu12;
    private javax.swing.JLabel DaftarMenu13;
    private javax.swing.JLabel DaftarMenu14;
    private javax.swing.JLabel DaftarMenu15;
    private javax.swing.JLabel DaftarMenu16;
    private javax.swing.JLabel DaftarMenu2;
    private javax.swing.JLabel DaftarMenu3;
    private javax.swing.JLabel DaftarMenu4;
    private javax.swing.JLabel DaftarMenu5;
    private javax.swing.JLabel DaftarMenu6;
    private javax.swing.JLabel DaftarMenu7;
    private javax.swing.JLabel DaftarMenu8;
    private javax.swing.JLabel DaftarMenu9;
    private javax.swing.JPanel Navbar;
    private javax.swing.JPanel Navbar1;
    private javax.swing.JPanel PanelBack21552011235;
    private javax.swing.JPanel PanelBack77174756;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel line6;
    private javax.swing.JLabel line7;
    private javax.swing.JLabel line8;
    // End of variables declaration//GEN-END:variables
}
