/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bendahara;
import petugas.*;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author albi mudakar
 */
public class dashboardBendahara extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    boolean a= true;
    public dashboardBendahara() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        //usernameBendahara21552011235.setText(username);
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        headerKelompok2 = new javax.swing.JPanel();
        iconMenu = new javax.swing.JPanel();
        PanelLogout21552011235 = new javax.swing.JPanel();
        BtnLogout21552011235 = new javax.swing.JLabel();
        BtnMax21552011235 = new javax.swing.JPanel();
        BtnMin21552011235 = new javax.swing.JPanel();
        menuKelompok2 = new javax.swing.JPanel();
        sidebarKelompok2 = new javax.swing.JPanel();
        homePanelKelompok2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnHomeKelompok2 = new javax.swing.JLabel();
        FormPanelKelompok2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        BtnFormKelompok2 = new javax.swing.JLabel();
        aboutPanelKelompok2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        BtnTentangKelompok2 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        DashboardviewKelompok2 = new javax.swing.JPanel();
        jTabbedPanelKelompok2 = new javax.swing.JTabbedPane();
        HomeTabbedKelompok2 = new javax.swing.JPanel();
        IconUser = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FormTabbedKelompok2 = new javax.swing.JPanel();
        PanelKelompok2 = new javax.swing.JPanel();
        TabHomePanelDataPendonorKelompok2 = new javax.swing.JPanel();
        TabFormDataPendonorKelompok2 = new javax.swing.JLabel();
        TabHomePanelTrasnfusiKelompok2 = new javax.swing.JPanel();
        TabFormPanelPasienKelompok2 = new javax.swing.JPanel();
        AboutTabbedKelompok2 = new javax.swing.JPanel();
        PanelAboutKelompok2 = new javax.swing.JPanel();
        TabAboutBtnKelompok2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);

        headerKelompok2.setBackground(new java.awt.Color(32, 83, 117));
        headerKelompok2.setPreferredSize(new java.awt.Dimension(800, 50));
        headerKelompok2.setLayout(new java.awt.BorderLayout());

        iconMenu.setBackground(new java.awt.Color(0, 0, 0));
        iconMenu.setPreferredSize(new java.awt.Dimension(150, 50));
        iconMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLogout21552011235.setBackground(new java.awt.Color(32, 83, 117));
        PanelLogout21552011235.setPreferredSize(new java.awt.Dimension(50, 50));
        PanelLogout21552011235.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnLogout21552011235.setBackground(new java.awt.Color(30, 23, 15));
        BtnLogout21552011235.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnLogout21552011235.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogout21552011235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnLogout21552011235.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-sign-out-20.png"))); // NOI18N
        BtnLogout21552011235.setText("Logout");
        BtnLogout21552011235.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLogout21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLogout21552011235MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLogout21552011235MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnLogout21552011235MouseExited(evt);
            }
        });
        PanelLogout21552011235.add(BtnLogout21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 50));

        iconMenu.add(PanelLogout21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 90, -1));

        BtnMax21552011235.setBackground(new java.awt.Color(32, 83, 117));
        BtnMax21552011235.setPreferredSize(new java.awt.Dimension(50, 50));
        BtnMax21552011235.setLayout(new java.awt.BorderLayout());
        iconMenu.add(BtnMax21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        BtnMin21552011235.setBackground(new java.awt.Color(32, 83, 117));
        BtnMin21552011235.setPreferredSize(new java.awt.Dimension(50, 50));
        BtnMin21552011235.setLayout(new java.awt.BorderLayout());
        iconMenu.add(BtnMin21552011235, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        headerKelompok2.add(iconMenu, java.awt.BorderLayout.LINE_END);

        getContentPane().add(headerKelompok2, java.awt.BorderLayout.PAGE_START);

        menuKelompok2.setBackground(new java.awt.Color(32, 83, 117));
        menuKelompok2.setPreferredSize(new java.awt.Dimension(270, 450));
        menuKelompok2.setLayout(new java.awt.BorderLayout());

        sidebarKelompok2.setBackground(new java.awt.Color(32, 83, 117));
        sidebarKelompok2.setMinimumSize(new java.awt.Dimension(200, 210));
        sidebarKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePanelKelompok2.setBackground(new java.awt.Color(32, 83, 117));
        homePanelKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePanelKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homePanelKelompok2MouseEntered(evt);
            }
        });
        homePanelKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-home-24.png"))); // NOI18N
        homePanelKelompok2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 43, 50));

        BtnHomeKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnHomeKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        BtnHomeKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnHomeKelompok2.setText("Home");
        BtnHomeKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnHomeKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnHomeKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnHomeKelompok2MouseExited(evt);
            }
        });
        homePanelKelompok2.add(BtnHomeKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        sidebarKelompok2.add(homePanelKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 270, 50));

        FormPanelKelompok2.setBackground(new java.awt.Color(32, 83, 117));
        FormPanelKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-doctors-folder-24.png"))); // NOI18N
        FormPanelKelompok2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 43, 50));

        BtnFormKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnFormKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        BtnFormKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnFormKelompok2.setText("Form");
        BtnFormKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnFormKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnFormKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnFormKelompok2MouseExited(evt);
            }
        });
        FormPanelKelompok2.add(BtnFormKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        sidebarKelompok2.add(FormPanelKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, -1));

        aboutPanelKelompok2.setBackground(new java.awt.Color(32, 83, 117));
        aboutPanelKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-info-24.png"))); // NOI18N
        aboutPanelKelompok2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 43, 50));

        BtnTentangKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnTentangKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        BtnTentangKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnTentangKelompok2.setText("About");
        BtnTentangKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnTentangKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnTentangKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnTentangKelompok2MouseExited(evt);
            }
        });
        aboutPanelKelompok2.add(BtnTentangKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        sidebarKelompok2.add(aboutPanelKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 270, 50));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pddm_100px-removebg-preview.png"))); // NOI18N
        sidebarKelompok2.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, 190, 130));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BackLOGO.png"))); // NOI18N
        sidebarKelompok2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 230, 110));

        menuKelompok2.add(sidebarKelompok2, java.awt.BorderLayout.CENTER);

        getContentPane().add(menuKelompok2, java.awt.BorderLayout.LINE_START);

        DashboardviewKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        DashboardviewKelompok2.setLayout(new java.awt.GridLayout(1, 0));

        jTabbedPanelKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        jTabbedPanelKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(64, 49, 33), new java.awt.Color(64, 49, 33), new java.awt.Color(64, 49, 33), new java.awt.Color(64, 49, 33)));
        jTabbedPanelKelompok2.setForeground(new java.awt.Color(17, 43, 60));

        HomeTabbedKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        HomeTabbedKelompok2.setLayout(new java.awt.GridBagLayout());

        IconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-male-user-96.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 258, 0, 0);
        HomeTabbedKelompok2.add(IconUser, gridBagConstraints);

        UserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UserName.setForeground(new java.awt.Color(255, 255, 255));
        UserName.setText("Bendahara");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(73, 14, 0, 0);
        HomeTabbedKelompok2.add(UserName, gridBagConstraints);

        usernameBendaharaKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameBendaharaKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(73, 14, 0, 0);
        HomeTabbedKelompok2.add(usernameBendaharaKelompok2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Persaudaraan Donor Darah Majalaya.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 196, 163, 140);
        HomeTabbedKelompok2.add(jLabel4, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Anda bisa mengelola keuangan ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 242, 0, 0);
        HomeTabbedKelompok2.add(jLabel7, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("___________________");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 301, 0, 0);
        HomeTabbedKelompok2.add(jLabel3, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dashboard Bendahara");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 242, 0, 0);
        HomeTabbedKelompok2.add(jLabel6, gridBagConstraints);

        jTabbedPanelKelompok2.addTab("", HomeTabbedKelompok2);

        FormTabbedKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        FormTabbedKelompok2.setLayout(new java.awt.GridBagLayout());

        PanelKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        PanelKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        PanelKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        FormTabbedKelompok2.add(PanelKelompok2, gridBagConstraints);

        TabHomePanelDataPendonorKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        TabHomePanelDataPendonorKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        TabHomePanelDataPendonorKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabFormDataPendonorKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TabFormDataPendonorKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        TabFormDataPendonorKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabFormDataPendonorKelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-money-96.png"))); // NOI18N
        TabFormDataPendonorKelompok2.setText("Keuangan");
        TabFormDataPendonorKelompok2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabFormDataPendonorKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabFormDataPendonorKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabFormDataPendonorKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabFormDataPendonorKelompok2MouseExited(evt);
            }
        });
        TabHomePanelDataPendonorKelompok2.add(TabFormDataPendonorKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 280));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(109, 45, 83, 31);
        FormTabbedKelompok2.add(TabHomePanelDataPendonorKelompok2, gridBagConstraints);

        TabHomePanelTrasnfusiKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        TabHomePanelTrasnfusiKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        TabHomePanelTrasnfusiKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        FormTabbedKelompok2.add(TabHomePanelTrasnfusiKelompok2, gridBagConstraints);

        TabFormPanelPasienKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        TabFormPanelPasienKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        TabFormPanelPasienKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        FormTabbedKelompok2.add(TabFormPanelPasienKelompok2, gridBagConstraints);

        jTabbedPanelKelompok2.addTab("", FormTabbedKelompok2);

        AboutTabbedKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        AboutTabbedKelompok2.setLayout(new java.awt.GridBagLayout());

        PanelAboutKelompok2.setBackground(new java.awt.Color(17, 43, 60));
        PanelAboutKelompok2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        PanelAboutKelompok2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabAboutBtnKelompok2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        TabAboutBtnKelompok2.setForeground(new java.awt.Color(255, 255, 255));
        TabAboutBtnKelompok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabAboutBtnKelompok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconOutline/icons8-info-96.png"))); // NOI18N
        TabAboutBtnKelompok2.setText("Tentang");
        TabAboutBtnKelompok2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabAboutBtnKelompok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabAboutBtnKelompok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabAboutBtnKelompok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabAboutBtnKelompok2MouseExited(evt);
            }
        });
        PanelAboutKelompok2.add(TabAboutBtnKelompok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 200));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(120, 130, 152, 74);
        AboutTabbedKelompok2.add(PanelAboutKelompok2, gridBagConstraints);

        jTabbedPanelKelompok2.addTab("", AboutTabbedKelompok2);

        DashboardviewKelompok2.add(jTabbedPanelKelompok2);

        getContentPane().add(DashboardviewKelompok2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(975, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    public void clickmenu (JPanel h1, JPanel h2, int numberbool){
//        if(numberbool == 1){
//            h1.setBackground(new Color(45,35,23));
//            h2.setBackground(new Color(20,15,10));
//        }else{
//            h1.setBackground(new Color(45,35,23));
//            h2.setBackground(new Color(20,15,10));
//        }
    }
    
    
     public void changeimage(JLabel button, String resourcheimg){
//        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
//        button.setIcon(aimg);
    }
    
    
//    
//    public void hideshow (JPanel menushowhide, boolean dashboard, JLabel button){
//        if (dashboard == true){
//            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
//            changeimage(button, "/iconOutline/icons8-menu-32.png");
//        }else{
//            menushowhide.setPreferredSize(new Dimension(200, menushowhide.getHeight()));
//            changeimage(button, "/iconOutline/icons8-back-32.png");
//        }
//    }
//    
   
    
    
    
    private void homePanelKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelKelompok2MouseEntered
        
    }//GEN-LAST:event_homePanelKelompok2MouseEntered

    private void homePanelKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelKelompok2MouseClicked

    }//GEN-LAST:event_homePanelKelompok2MouseClicked

    private void BtnHomeKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHomeKelompok2MouseEntered
        changecolor(homePanelKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_BtnHomeKelompok2MouseEntered

    private void BtnHomeKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHomeKelompok2MouseExited
        changecolor(homePanelKelompok2, new Color (32,83,117));
    }//GEN-LAST:event_BtnHomeKelompok2MouseExited

    private void BtnFormKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFormKelompok2MouseEntered
       changecolor(FormPanelKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_BtnFormKelompok2MouseEntered

    private void BtnFormKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFormKelompok2MouseExited
        changecolor(FormPanelKelompok2, new Color (32,83,117));
    }//GEN-LAST:event_BtnFormKelompok2MouseExited

    private void BtnTentangKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTentangKelompok2MouseEntered
        changecolor(aboutPanelKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_BtnTentangKelompok2MouseEntered

    private void BtnTentangKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTentangKelompok2MouseExited
        changecolor(aboutPanelKelompok2, new Color (32,83,117));
    }//GEN-LAST:event_BtnTentangKelompok2MouseExited

    private void BtnLogout21552011235MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogout21552011235MouseExited
        changecolor(PanelLogout21552011235, new Color (32,83,117));
    }//GEN-LAST:event_BtnLogout21552011235MouseExited

    private void BtnLogout21552011235MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogout21552011235MouseEntered
        changecolor(PanelLogout21552011235, new Color (255,24,24));
    }//GEN-LAST:event_BtnLogout21552011235MouseEntered

    private void BtnLogout21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogout21552011235MouseClicked
        new login.loginUser().setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnLogout21552011235MouseClicked

    private void BtnHomeKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHomeKelompok2MouseClicked
       jTabbedPanelKelompok2.setSelectedIndex(0);
    }//GEN-LAST:event_BtnHomeKelompok2MouseClicked

    private void BtnFormKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFormKelompok2MouseClicked
        jTabbedPanelKelompok2.setSelectedIndex(1);
    }//GEN-LAST:event_BtnFormKelompok2MouseClicked

    private void BtnTentangKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTentangKelompok2MouseClicked
        jTabbedPanelKelompok2.setSelectedIndex(2);
    }//GEN-LAST:event_BtnTentangKelompok2MouseClicked

    private void TabAboutBtnKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabAboutBtnKelompok2MouseExited
        changecolor(PanelAboutKelompok2, new Color (17,43,60));
    }//GEN-LAST:event_TabAboutBtnKelompok2MouseExited

    private void TabAboutBtnKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabAboutBtnKelompok2MouseEntered
        changecolor(PanelAboutKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_TabAboutBtnKelompok2MouseEntered

    private void TabAboutBtnKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabAboutBtnKelompok2MouseClicked
        new bendahara.AboutBendahara().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabAboutBtnKelompok2MouseClicked

    private void TabFormDataPendonorKelompok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabFormDataPendonorKelompok2MouseExited
        changecolor(TabHomePanelDataPendonorKelompok2, new Color (17,43,60));
    }//GEN-LAST:event_TabFormDataPendonorKelompok2MouseExited

    private void TabFormDataPendonorKelompok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabFormDataPendonorKelompok2MouseEntered
        changecolor(TabHomePanelDataPendonorKelompok2, new Color (32,108,151));
    }//GEN-LAST:event_TabFormDataPendonorKelompok2MouseEntered

    private void TabFormDataPendonorKelompok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabFormDataPendonorKelompok2MouseClicked
        new bendahara.FormKeuangan().setVisible(true);
        dispose();
    }//GEN-LAST:event_TabFormDataPendonorKelompok2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardBendahara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardBendahara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardBendahara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardBendahara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new dashboardBendahara().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutTabbedKelompok2;
    private javax.swing.JLabel BtnFormKelompok2;
    private javax.swing.JLabel BtnHomeKelompok2;
    private javax.swing.JLabel BtnLogout21552011235;
    private javax.swing.JPanel BtnMax21552011235;
    private javax.swing.JPanel BtnMin21552011235;
    private javax.swing.JLabel BtnTentangKelompok2;
    private javax.swing.JPanel DashboardviewKelompok2;
    private javax.swing.JPanel FormPanelKelompok2;
    private javax.swing.JPanel FormTabbedKelompok2;
    private javax.swing.JPanel HomeTabbedKelompok2;
    private javax.swing.JLabel IconUser;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PanelAboutKelompok2;
    private javax.swing.JPanel PanelKelompok2;
    private javax.swing.JPanel PanelLogout21552011235;
    private javax.swing.JLabel TabAboutBtnKelompok2;
    private javax.swing.JLabel TabFormDataPendonorKelompok2;
    private javax.swing.JPanel TabFormPanelPasienKelompok2;
    private javax.swing.JPanel TabHomePanelDataPendonorKelompok2;
    private javax.swing.JPanel TabHomePanelTrasnfusiKelompok2;
    private javax.swing.JLabel UserName;
    private javax.swing.JPanel aboutPanelKelompok2;
    private javax.swing.JPanel headerKelompok2;
    private javax.swing.JPanel homePanelKelompok2;
    private javax.swing.JPanel iconMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPanelKelompok2;
    private javax.swing.JPanel menuKelompok2;
    private javax.swing.JPanel sidebarKelompok2;
    public static final javax.swing.JLabel usernameBendaharaKelompok2 = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

    private static class color {

        public color() {
        }
    }

    private static class Jpanel {

        public Jpanel() {
        }

        private void setbackground(color rand) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

    private static class jTabbedPanel {

        public jTabbedPanel() {
        }
    }
}
